import { langs } from '@uiw/codemirror-extensions-langs'

export const themesOptions: ({ label: string; value: string } | 'separator')[] = [
	{ label: 'Light', value: 'light' },
	{ label: 'bbedit', value: 'bbedit' },
	{ label: 'eclipse', value: 'eclipse' },
	{ label: 'github light', value: 'githubLight' },
	{ label: 'material light', value: 'materialLight' },
	{ label: 'noctis lilac', value: 'noctisLilac' },
	{ label: 'xcode light', value: 'xcodeLight' },
	'separator',
	{ label: 'Dark', value: 'dark' },
	{ label: 'android studio', value: 'androidstudio' },
	{ label: 'dracula', value: 'dracula' },
	{ label: 'github dark', value: 'githubDark' },
	{ label: 'material dark', value: 'materialDark' },
	{ label: 'monokai', value: 'monokai' },
	{ label: 'vscode dark', value: 'vscodeDark' },
	{ label: 'xcode dark', value: 'xcodeDark' },
]

export const FILE_EXT_LANG_MAP = {
	c: 'c',
	cpp: 'cpp',
	cs: 'csharp',
	css: 'css',
	dart: 'dart',
	erl: 'erlang',
	go: 'go',
	htm: 'html',
	html: 'html',
	java: 'java',
	jl: 'julia',
	js: 'javascript',
	jsx: 'jsx',
	json: 'json',
	kt: 'kotlin',
	less: 'less',
	lua: 'lua',
	md: 'markdown',
	php: 'php',
	pl: 'perl',
	pm: 'perl',
	ps: 'powershell',
	py: 'python',
	r: 'r',
	rb: 'ruby',
	rs: 'rust',
	sass: 'sass',
	scala: 'scala',
	scss: 'sass',
	sh: 'shell',
	sql: 'sql',
	swift: 'swift',
	toml: 'toml',
	ts: 'typescript',
	tsx: 'tsx',
	vb: 'vb',
	vue: 'vue',
	wast: 'wast',
	xml: 'xml',
	yaml: 'yaml',
}

export type FILE_EXT_LANG_MAP_KEY = keyof typeof FILE_EXT_LANG_MAP
export type LangsKey = keyof typeof langs
